# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
  kind: "ConfigMap"
  apiVersion: "v1"
  metadata:
    name: "platform"
    labels:
      id: "platform"
  data:
    domain: "example.com"
    tap-version: "0.8"
    cli-version: "0.8"
    cdh-version: "5.4"
    k8s-version: "1.3.0"
    core-organization: "trustedanalytics-ng"
---
  kind: "ConfigMap"
  apiVersion: "v1"
  metadata:
    name: "api-service-credentials"
    labels:
      id: "api-service-credentials"
  data:
    api-service-port: "80"
    api-service-user: "admin"
    api-service-pass: "password"
    api-service-ssl-cert-file-location: ""
    api-service-ssl-key-file-location: ""
    api-service-ssl-ca-file-location: ""
    insecure-skip-verify: "true"
    broker-log-level: "DEBUG"
    template-repository-kubernetes-service-name: "TEMPLATE_REPOSITORY"
    template-repository-user: "admin"
    template-repository-pass: "password"
    template-repository-ssl-cert-file-location: ""
    template-repository-ssl-key-file-location: ""
    template-repository-ssl-ca-file-location: ""
    catalog-kubernetes-service-name: "CATALOG"
    catalog-user: "admin"
    catalog-pass: "password"
    catalog-ssl-cert-file-location: ""
    catalog-ssl-key-file-location: ""
    catalog-ssl-ca-file-location: ""
    container-broker-kubernetes-service-name: "CONTAINER_BROKER"
    container-broker-user: "admin"
    container-broker-pass: "password"
    container-broker-ssl-cert-file-location: ""
    container-broker-ssl-key-file-location: ""
    container-broker-ssl-ca-file-location: ""
    blob-store-kubernetes-service-name: "BLOB_STORE"
    blob-store-port: "80"
    blob-store-user: "admin"
    blob-store-pass: "password"
    blob-store-ssl-cert-file-location: ""
    blob-store-ssl-key-file-location: ""
    blob-store-ssl-ca-file-location: ""
    image-factory-kubernetes-service-name: "IMAGE_FACTORY"
    image-factory-port: "80"
    image-factory-user: "admin"
    image-factory-pass: "password"
    image-factory-ssl-cert-file-location: ""
    image-factory-ssl-key-file-location: ""
    image-factory-ssl-ca-file-location: ""
    image-factory-hub-address: "127.0.0.1:5000"
